# Generated by Django 3.1.14 on 2022-11-08 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizations',
            options={'verbose_name_plural': 'Organizations'},
        ),
        migrations.AlterModelOptions(
            name='orggroups',
            options={'verbose_name_plural': 'OrgGroups'},
        ),
    ]
