# Generated by Django 3.1.14 on 2022-11-10 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0002_auto_20221108_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orggroups',
            old_name='groupId',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='orggroups',
            old_name='userId',
            new_name='user',
        ),
    ]
